### ISSUE TITLE
Not able to load Story (connect to api)

### ISSUE THREAD

**Issue by katariyanikhil** [InvertedX/instory#5]
After I enter username in the field its says check your connection every time I tried please re check the code and help me with the issue.

**Comment by katariyanikhil** [comment]
Also I think the api you are using is not working now try to replace it with working api

**Comment by jmartle** [comment]
have you found any apps similar to this one on github that works?

**Comment by katariyanikhil** [comment]
No I have not but i am trying to make one but only issue i am facing is how to make user login with instagram implement as this app was doing the rest is almost done.
